openapi: 3.0.0
info:
  title: Gym Application API
  description: API for everything
  version: 1.0.0
servers:
  - url: http://localhost:8123/api
    description: Local server

paths:
  /trainees/{username}:
    get:
      tags:
        - trainees
      summary: Get trainee by username
      parameters:
        - name: username
          in: path
          description: Username of the trainee
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TraineeResponseDTO'
    delete:
      tags:
        - trainees
      summary: Delete trainee by username
      parameters:
        - name: username
          in: path
          description: Username of the trainee to delete
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Trainee deleted successfully
  /trainees:
    post:
      tags:
        - trainees
      summary: Add a new trainee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TraineeRegistrationDTO'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsernameAndPasswordDTO'
    put:
      tags:
        - trainees
      summary: Update a trainee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TraineeUpdateRequestDTO'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TraineeUpdateResponseDTO'
  /trainees/activate:
    patch:
      tags:
        - trainees
      summary: Activate trainee
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/ActivationDTO'
      responses:
        '200':
          description: Trainee activated successfully
  /trainees/deactivate:
    patch:
      tags:
        - trainees
      summary: Deactivate trainee
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/ActivationDTO'
      responses:
        '200':
          description: Trainee deactivated successfully
  /trainees/trainers:
    put:
      tags:
        - trainees
      summary: Update trainers list for a trainee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TraineeUpdateTrainerListDTO'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TraineesTrainerResponseDTO'
  /trainees/trainings:
    get:
      tags:
        - trainees
      summary: Get trainee's training list based on criteria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TraineeTrainingCriteriaDTO'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TraineeTrainingResponseDTO'
  /trainers/{username}:
    get:
      tags:
        - trainers
      summary: Get trainer by username
      parameters:
        - name: username
          in: path
          description: Username of the trainer
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainerResponseDTO'
  /trainers:
    post:
      tags:
        - trainers
      summary: Add new trainer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainerRegistrationDTO'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsernameAndPasswordDTO'
    put:
      tags:
        - trainers
      summary: Update trainer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainerUpdateRequestDTO'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainerUpdateResponseDTO'  
    get:
      tags:
        - trainers
      summary: Get not assigned active trainers list
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NotAssignedTrainerResponseDTO'
  /trainers/trainings:
    get:
      tags:
        - trainers
      summary: Get trainer's training list based on criteria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainerTrainingCriteriaDTO'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrainerTrainingResponseDTO'
  /trainers/activate:
    patch:
      tags:
        - trainers
      summary: Activate trainee
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/ActivationDTO'
      responses:
        '200':
          description: Trainer activated successfully
  /trainers/deactivate:
    patch:
      tags:
        - trainers
      summary: deactivate trainee
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/ActivationDTO'
      responses:
        '200':
          description: Trainer activated successfully
  /trainings:
    post:
      tags:
        - trainings
      summary: Add a new training
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainingPostDTO'
      responses:
        '200':
          description: Training created successfully
  /training-types:
    get:
      tags:
        - training types
      summary: Get all training types
      responses:
        '200':
          description: List of training types
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrainingTypeDTO'
components:
  schemas:
    TraineeResponseDTO:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
          format: date
        address:
          type: string
        isActive:
          type: boolean
        trainers:
          type: array
          items:
            $ref: '#/components/schemas/TraineesTrainerResponseDTO'
    TraineesTrainerResponseDTO:
      type: object
      properties:
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        specialization:
          type: integer
          format: int64
    TraineeRegistrationDTO:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
          format: date
        address:
          type: string
      required:
        - firstName
        - lastName
    UsernameAndPasswordDTO:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    TraineeUpdateRequestDTO:
      type: object
      properties:
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
          format: date
        address:
          type: string
        isActive:
          type: boolean
      required:
        - username
        - firstName
        - lastName
        - isActive
    TraineeUpdateResponseDTO:
      type: object
      properties:
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
          format: date
        address:
          type: string
        isActive:
          type: boolean
        trainers:
          type: array
          items:
            $ref: '#/components/schemas/TraineesTrainerResponseDTO'
    ActivationDTO:
      type: object
      properties:
        username:
          type: string
          description: Username of the trainee
        isActive:
          type: boolean
          description: Activation status of the trainee
      required:
        - username
    TraineeUpdateTrainerListDTO:
      type: object
      properties:
        username:
          type: string
          description: Username of the trainee
        trainers:
          type: array
          items:
            type: string
      required:
        - username
        - trainers
    TraineeTrainingCriteriaDTO:
      type: object
      properties:
        username:
          type: string
          description: Username of the trainee
        from:
          type: string
          format: date
          description: Start date of the training period
        to:
          type: string
          format: date
          description: End date of the training period
        trainerName:
          type: string
          description: Name of the trainer
        trainingType:
          type: string
          description: Type of training
      required:
        - username
    TraineeTrainingResponseDTO:
      type: object
      properties:
        trainingName:
          type: string
        trainingDate:
          type: string
          format: date
        trainingType:
          $ref: '#/components/schemas/TrainingTypeDTO'
        trainingDuration:
          type: integer
          format: int64
        trainerName:
          type: string
    TrainingTypeDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Id of training type
        name:
          type: string
          description: Name of training type
    TrainerResponseDTO:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        specialization:
          type: integer
          format: int64
        address:
          type: string
        isActive:
          type: boolean
        trainees:
          type: array
          items:
            $ref: '#/components/schemas/TrainersTraineeDTO'
    TrainersTraineeDTO:
      type: object
      properties:
        username: 
          type: string
        firstName:
          type: string
        lastName:
          type: string
    TrainerRegistrationDTO:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        specialization:
          type: integer
          format: int64
      required:
        - firstName
        - lastName
        - specialization
    TrainerUpdateRequestDTO:
      type: object
      properties:
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        specialization:
          type: integer
          format: int64
        isActive:
          type: boolean
      required:
        - username
        - firstName
        - lastName
        - isActive
    TrainerUpdateResponseDTO:
      type: object
      properties:
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        specialization:
          type: integer
          format: int64
        address:
          type: string
        isActive:
          type: boolean
        trainees:
          type: array
          items:
            $ref: '#/components/schemas/TrainersTraineeDTO'
    NotAssignedTrainerResponseDTO:
      type: object
      properties:
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        specialization:
          type: integer
          format: int64
    TrainerTrainingCriteriaDTO:
      type: object
      properties:
        username:
          type: string
          description: Username of the trainer
        from:
          type: string
          format: date
          description: Start date of the training period
        to:
          type: string
          format: date
          description: End date of the training period
        traineeName:
          type: string
          description: Name of the trainee
      required:
        - username
    TrainerTrainingResponseDTO:
      type: object
      properties:
        trainingName:
          type: string
        trainingDate:
          type: string
          format: date
        trainingType:
          $ref: '#/components/schemas/TrainingTypeDTO'
        trainingDuration:
          type: integer
          format: int64
        traineeName:
          type: string
    TrainingPostDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        traineeUsername:
          type: string
          description: Trainee username
        trainerUsername:
          type: string
          description: Trainer username
        trainingName:
          type: string
          description: Name of the training
        trainingDate:
          type: string
          format: date
          description: Date of the training
        trainingDuration:
          type: integer
          format: int64
          description: Duration of the training in minutes
        trainingTypeName:
          type: string
          description: Type of the training
      required:
        - traineeUsername
        - trainerUsername
        - trainingName
        - trainingDate
        - trainingDuration
        - trainingTypeName